spring.application.name=appointmentmangement
server.port=9194
spring.datasource.url=jdbc:postgresql://localhost:5432/AppointmentSystem
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=W@2915djkq#
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohekarsiddhant03@gmail.com
spring.mail.password=uwqprbrontzdxemr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.endpoints.web.exposure.include=*


