spring.application.name=appointmentmangement
server.port=9194
spring.datasource.url=jdbc:postgresql://localhost:5432/AppointmentSystem
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=W@2915djkq#
spring.jpa.hibernate.ddl-auto=update


